=== tagart/javaSamples/javaSamples/resources/catalog.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:simpleType name="restrictedDecimal">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="14" />
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="12" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="title" type="xs:string" />
            <xs:element name="price" type="restrictedDecimal"/>
            <xs:element name="item" type="itemType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" type="itemType" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tagart/javaSamples/javaSamples/resources/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<list
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='catalog.xsd'>
    <item>
        <id>1</id>
        <title>Наименование 1</title>
        <price>1</price>
        <item>
            <id>2</id>
            <title>Наименование 2</title>
            <price>2</price>
        </item>
        <item>
            <id>3</id>
            <title>Наименование 3</title>
            <price>3</price>
        </item>
    </item>
    <item>
        <id>4</id>
        <title>Наименование 4</title>
        <price>4</price>
    </item>
    <item>
        <id>5</id>
        <title>Наименование 5</title>
        <price>5</price>
    </item>
</list>
